version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: production
    ports:
      - '3002:3000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
  mongodb:
    image: mongo:6.0
    container_name: mongodb-medical-records
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: medical-records
      MONGO_URI: mongodb://mongodb:27017/medical-records
    volumes:
      - mongo_data:/data/db
    restart: always
  medical-records:
    build:
      context: .
      dockerfile: ./apps/medical-records/Dockerfile
      target: production
    ports:
      - '3003:3000'
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - .env

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: production
    ports:
      - '3000:3000'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - APPOINTMENTS_QUEUE=${APPOINTMENTS_QUEUE}
    depends_on:
      - rabbitmq
      - appointments
      - medical-records
      - users
      - symptom-checker
    env_file:
      - .env

  appointments:
    build:
      context: .
      dockerfile: ./apps/appointments/Dockerfile
    ports:
      - '3001:3000'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@appointments-db:5432/${APPOINTMENTS_DB}?schema=public
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - APPOINTMENTS_QUEUE=${APPOINTMENTS_QUEUE}
      - PORT=3001
    depends_on:
      - appointments-db
      - rabbitmq

  symptom-checker:
    build:
      context: .
      dockerfile: ./apps/symptom-checker/Dockerfile
    ports:
      - '3010:3000'
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - SYMPTOM_CHECKER_QUEUE=${SYMPTOM_CHECKER_QUEUE}
      - PORT=3010
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - rabbitmq
  appointments-db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - appointments_db_data:/var/lib/postgresql/data
    restart: always

  doctor:
    build:
      context: .
      dockerfile: ./apps/doctor/Dockerfile
      target: production
    ports:
      - '3004:3000'
    depends_on:
      - rabbitmq
      - mongodb
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      # - MONGO_URL=mongodb://mongodb:27017/medical-records

volumes:
  mongo_data:
  appointments_db_data:
