export const APPOINTMENTS_SERVICE = Symbol('APPOINTMENTS_SERVICE');
export const DOCTOR_SERVICE = Symbol('DOCTOR_SERVICE');
export const NOTIFICATIONS_SERVICE = Symbol('NOTIFICATIONS_SERVICE');
export const RECORDS_SERVICE = Symbol('RECORDS_SERVICE');
export const USERS_SERVICE = Symbol('USERS_SERVICE');
